"""`a2f` command-line interface."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import click

from . import __version__
from . import state as _state
from .deploy import deploy_generated_notebooks, deploy_pipeline
from .fabric_api import FabricClient
from .onelake import OneLake
from .parse import parse_yxmd, save_ir, summarise
from .run import run_pipeline_and_wait
from .validate import diff_folders, format_report


# ----------------------------- helpers -----------------------------
def _project_root() -> str:
    return os.getcwd()


def _get_client_or_exit() -> FabricClient:
    st = _state.load(_project_root())
    ws = st.get("workspace_id") or os.environ.get("A2F_WORKSPACE_ID")
    if not ws:
        click.secho(
            "Error: workspace_id not set. Run `a2f init <name> --workspace-id <guid>` "
            "or set A2F_WORKSPACE_ID.",
            fg="red",
        )
        sys.exit(2)
    return FabricClient(ws)


# ----------------------------- root group -----------------------------
@click.group()
@click.version_option(__version__, prog_name="a2f")
def main():
    """alteryx2fabric — migrate Alteryx workflows to Microsoft Fabric."""


# ----------------------------- init -----------------------------
@main.command()
@click.argument("name")
@click.option("--workspace-id", required=True, help="Fabric workspace GUID.")
@click.option("--lakehouse-name", default=None, help="Lakehouse display name to use (default: <name>_LH).")
def init(name: str, workspace_id: str, lakehouse_name: str | None):
    """Scaffold a new migration project in ./<NAME>/."""
    root = Path(name)
    if root.exists():
        click.secho(f"Refusing to overwrite existing path: {root}", fg="red")
        sys.exit(2)
    for d in ("inputs", "reference_outputs", "fabric_outputs", "notebooks", ".a2f"):
        (root / d).mkdir(parents=True, exist_ok=True)
    state = {
        "project_name": name,
        "workspace_id": workspace_id,
        "lakehouse_name": lakehouse_name or f"{name}_LH",
    }
    _state.save(state, root)
    (root / "README.md").write_text(
        f"# {name}\n\nGenerated by alteryx2fabric.\n\n"
        "- `inputs/`            — source files to upload to OneLake\n"
        "- `reference_outputs/` — Alteryx-produced files used for validation\n"
        "- `fabric_outputs/`    — files downloaded from Fabric after a run\n"
        "- `notebooks/`         — generated `.ipynb` cache\n"
        "- `.a2f/state.json`    — Fabric IDs for subsequent commands\n",
        encoding="utf-8",
    )
    click.secho(f"Initialised project: {root.resolve()}", fg="green")
    click.echo(f"  workspace_id  = {workspace_id}")
    click.echo(f"  lakehouse     = {state['lakehouse_name']}")


# ----------------------------- doctor -----------------------------
@main.command()
@click.option("--json-output", "as_json", is_flag=True, help="Emit structured JSON for automation.")
@click.option("--offline", is_flag=True, help="Run local checks without contacting Azure or Fabric.")
def doctor(as_json: bool, offline: bool):
    """Check local artifacts, Azure authentication, and Fabric access."""
    from .preflight import exit_code, run_checks
    checks = run_checks(_project_root(), online=not offline)
    if as_json:
        click.echo(json.dumps({"checks": [check.as_dict() for check in checks]}, indent=2))
    else:
        colors = {"pass": "green", "warn": "yellow", "fail": "red"}
        for check in checks:
            click.secho(f"[{check.status.upper():4}] {check.name}: {check.message}", fg=colors[check.status])
    if exit_code(checks):
        sys.exit(2)


# ----------------------------- parse -----------------------------
@main.command()
@click.argument("yxmd_path")
@click.option("--out", "out_path", default="ir.json", help="Where to write the IR JSON.")
def parse(yxmd_path: str, out_path: str):
    """Parse an Alteryx workflow into a JSON Intermediate Representation."""
    ir = parse_yxmd(yxmd_path)
    save_ir(ir, out_path)
    click.echo(summarise(ir))
    click.secho(f"\nIR written: {out_path}", fg="green")


@main.command("plan")
@click.argument("source", required=False)
@click.option("--ir", "ir_path", default="ir.json", help="Existing IR JSON path.")
@click.option("--out", "out_path", default=".a2f/migration-plan.json", help="Plan JSON path.")
@click.option("--markdown", "markdown_path", default=".a2f/migration-plan.md", help="Plan Markdown path.")
def plan_cmd(source: str | None, ir_path: str, out_path: str, markdown_path: str):
    """Create a deterministic migration plan from a YXMD or existing IR."""
    from .plan import build_plan, format_plan, save_plan
    if source:
        ir = parse_yxmd(source)
    else:
        ir = _load_ir(ir_path)
    migration_plan = build_plan(ir, source)
    save_plan(migration_plan, out_path, markdown_path)
    click.echo(format_plan(migration_plan))
    click.secho(f"Plan written: {out_path} and {markdown_path}", fg="green")


# ----------------------------- provision -----------------------------
@main.command()
@click.option("--lakehouse", "lakehouse_name", default=None, help="Lakehouse name (defaults to state).")
def provision(lakehouse_name: str | None):
    """Create the Lakehouse in the workspace."""
    client = _get_client_or_exit()
    st = _state.load(_project_root())
    name = lakehouse_name or st.get("lakehouse_name")
    if not name:
        click.secho("lakehouse name not provided", fg="red"); sys.exit(2)
    lh = client.create_lakehouse(name)
    click.secho(f"Lakehouse ready: {lh['displayName']} ({lh['id']})", fg="green")
    _state.update({"lakehouse_id": lh["id"], "lakehouse_name": lh["displayName"]}, _project_root())


# ----------------------------- upload -----------------------------
@main.command()
@click.argument("local_dir")
@click.option("--to", "remote_prefix", default="Input", help="Remote subfolder under Files/.")
def upload(local_dir: str, remote_prefix: str):
    """Upload all files under LOCAL_DIR to OneLake Files/<TO>/."""
    st = _state.load(_project_root())
    ws = st.get("workspace_id")
    lakehouse = st.get("lakehouse_id") or st.get("lakehouse_name")
    if not (ws and lakehouse):
        click.secho("workspace_id / lakehouse_name missing — run init + provision first.", fg="red")
        sys.exit(2)
    ol = OneLake(ws, lakehouse)
    src = Path(local_dir)
    n = 0
    for p in sorted(src.iterdir()):
        if p.is_file():
            size = ol.upload(p, f"{remote_prefix}/{p.name}")
            click.echo(f"uploaded {p.name} ({size} bytes)")
            n += 1
    click.secho(f"{n} files uploaded to Files/{remote_prefix}/", fg="green")


# ----------------------------- deploy -----------------------------
@main.command()
@click.option("--notebooks-dir", default="notebooks", help="Directory containing generated notebook bodies.")
@click.option("--prefix", default="Nb", help="Notebook name prefix.")
@click.option("--pipeline-name", default=None, help="Data Pipeline name (default: PL_<project>_Run).")
@click.option("--ir", "ir_path", default="ir.json", help="IR JSON path (for pipeline parameters).")
@click.option("--no-parameters", is_flag=True, help="Skip parameterizing the pipeline from the IR.")
def deploy(notebooks_dir: str, prefix: str, pipeline_name: str | None,
           ir_path: str, no_parameters: bool):
    """Deploy Bronze/Silver/Gold notebooks and the orchestration pipeline."""
    client = _get_client_or_exit()
    st = _state.load(_project_root())
    lh_id = st.get("lakehouse_id")
    lh_name = st.get("lakehouse_name")
    if not lh_id:
        click.secho("Lakehouse not provisioned. Run `a2f provision` first.", fg="red"); sys.exit(2)

    # Pull pipeline parameters from the IR (if present)
    parameters: list[dict] = []
    if not no_parameters and Path(ir_path).exists():
        try:
            ir = json.loads(Path(ir_path).read_text(encoding="utf-8"))
            parameters = ir.get("parameters", []) or []
            if parameters:
                click.echo(f"Detected {len(parameters)} parameter(s) from {ir_path}:")
                for p in parameters:
                    click.echo(f"  - {p['name']} ({p['source']}:{p['type']}) default={p.get('default','')!r}")
        except (OSError, json.JSONDecodeError, KeyError, TypeError) as e:
            click.secho(f"Could not load parameters from {ir_path}: {e}", fg="yellow")

    try:
        nb_ids = deploy_generated_notebooks(
            client, notebooks_dir, lh_id, lh_name, prefix=prefix
        )
    except (FileNotFoundError, ValueError) as e:
        click.secho(str(e), fg="red")
        sys.exit(2)
    for name, _id in nb_ids.items():
        click.echo(f"  notebook {name}: {_id}")

    pl_name = pipeline_name or f"PL_{st.get('project_name', 'Migration')}_Run"
    chain = [
        ("Bronze Ingest", nb_ids[f"{prefix}_Bronze_Ingest"]),
        ("Silver Transform", nb_ids[f"{prefix}_Silver_Transform"]),
        ("Gold Outputs", nb_ids[f"{prefix}_Gold_Outputs"]),
    ]
    pid = deploy_pipeline(client, pl_name, chain, parameters=parameters)
    click.secho(f"Pipeline {pl_name}: {pid}", fg="green")
    _state.update(
        {"notebooks": nb_ids, "pipeline_name": pl_name, "pipeline_id": pid,
         "parameters": parameters},
        _project_root(),
    )


# ----------------------------- run -----------------------------
@main.command()
@click.option("--pipeline", "pipeline_name", default=None, help="Pipeline name (default: from state).")
@click.option("--timeout", default=1800, help="Timeout in seconds.")
@click.option("--param", "params", multiple=True,
              help="Pipeline parameter override as name=value. Repeatable.")
def run(pipeline_name: str | None, timeout: int, params: tuple[str, ...]):
    """Trigger the pipeline and stream status."""
    client = _get_client_or_exit()
    st = _state.load(_project_root())
    pid = st.get("pipeline_id")
    if pipeline_name:
        item = client.find_item(pipeline_name, "DataPipeline")
        if not item:
            click.secho(f"Pipeline '{pipeline_name}' not found.", fg="red"); sys.exit(2)
        pid = item["id"]
    if not pid:
        click.secho("No pipeline id — run `a2f deploy` first or pass --pipeline.", fg="red"); sys.exit(2)

    # Parse --param name=value pairs, coerce against pipeline-declared types
    runtime_params: dict = {}
    if params:
        declared = {p["name"]: p for p in (st.get("parameters") or [])}
        for kv in params:
            if "=" not in kv:
                click.secho(f"--param expects name=value, got {kv!r}", fg="red"); sys.exit(2)
            k, v = kv.split("=", 1)
            decl = declared.get(k, {})
            t = decl.get("type", "string")
            if t == "int":
                runtime_params[k] = int(v)
            elif t == "bool":
                runtime_params[k] = v.strip().lower() in {"1", "true", "yes"}
            elif t == "array":
                runtime_params[k] = [s for s in v.split(",") if s]
            else:
                runtime_params[k] = v
        click.echo(f"Runtime parameters: {runtime_params}")

    click.echo(f"Triggering pipeline {pid} ...")
    _status_url, progress, final = run_pipeline_and_wait(
        client, pid, timeout_s=timeout, parameters=runtime_params or None
    )
    for elapsed, status in progress:
        click.echo(f"  [{elapsed}s] status={status}")
    click.echo("Final:")
    click.echo(json.dumps(final, indent=2)[:1500])
    if final.get("status") != "Completed":
        sys.exit(1)


# ----------------------------- download -----------------------------
@main.command()
@click.argument("remote_path")
@click.option("--out", "out_dir", default="fabric_outputs", help="Local destination dir.")
def download(remote_path: str, out_dir: str):
    """Download a file or all files in a remote folder from OneLake Files/."""
    st = _state.load(_project_root())
    ws = st.get("workspace_id")
    lakehouse = st.get("lakehouse_id") or st.get("lakehouse_name")
    ol = OneLake(ws, lakehouse)
    dest = Path(out_dir); dest.mkdir(parents=True, exist_ok=True)
    relative_path = remote_path.split("Files/", 1)[-1]
    # Try as folder first
    try:
        paths = ol.list_dir(relative_path)
        files = [p for p in paths if not p.get("isDirectory")]
        if files:
            for p in files:
                # path looks like Files/<remote_path>/foo.xlsx
                name = p["name"].split("/")[-1]
                full_remote = p["name"].split("Files/", 1)[-1]
                ol.download(full_remote, dest / name)
                click.echo(f"  downloaded {name} ({p.get('contentLength')} bytes)")
            return
    except RuntimeError:
        paths = []
    # Fall back to single file
    name = relative_path.rsplit("/", 1)[-1]
    ol.download(relative_path, dest / name)
    click.echo(f"  downloaded {name}")


# ----------------------------- validate -----------------------------
@main.command()
@click.option("--ref", "ref_dir", required=True, help="Reference output folder.")
@click.option("--gen", "gen_dir", required=True, help="Generated (Fabric) output folder.")
@click.option("--atol", default=1e-3, help="Numeric tolerance.")
def validate(ref_dir: str, gen_dir: str, atol: float):
    """Diff two folders of result files (xlsx/csv/parquet)."""
    results = diff_folders(ref_dir, gen_dir, atol=atol)
    click.echo(format_report(results))
    if not all(r.passed for r in results):
        sys.exit(1)


# ----------------------------- AI commands -----------------------------
def _llm(provider: str, model: str | None):
    from .ai import LLMClient
    return LLMClient(provider=provider, model=model)


def _load_ir(ir_path: str) -> dict:
    p = Path(ir_path)
    if not p.exists():
        click.secho(f"IR not found at {ir_path}. Run `a2f parse <yxmd> --out ir.json` first.", fg="red")
        sys.exit(2)
    return json.loads(p.read_text(encoding="utf-8"))


@main.group()
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github",
              help="LLM provider. github = GitHub Models (uses GITHUB_TOKEN/gh auth).")
@click.option("--model", default=None, help="Model id override (e.g. anthropic/claude-opus-4).")
@click.option("--ir", "ir_path", default="ir.json", help="Path to IR JSON from `a2f parse`.")
@click.pass_context
def generate(ctx, provider, model, ir_path):
    """AI-assisted notebook generation."""
    ctx.ensure_object(dict)
    ctx.obj["llm"] = _llm(provider, model)
    ctx.obj["ir"] = _load_ir(ir_path)


@generate.command("bronze")
@click.option("--inputs", "inputs_dir", default="inputs", help="Local inputs directory.")
@click.option("--out", "out_path", default="notebooks/nb_bronze.py", help="Output file.")
@click.pass_context
def generate_bronze_cmd(ctx, inputs_dir, out_path):
    """Generate the Bronze notebook body from the IR + local input headers."""
    from .generate import generate_bronze
    code = generate_bronze(ctx.obj["ir"], Path(inputs_dir), ctx.obj["llm"])
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(code, encoding="utf-8")
    click.echo(f"Wrote {out_path} ({len(code)} chars)")


@generate.command("silver")
@click.option("--out", "out_path", default="notebooks/nb_silver.py")
@click.pass_context
def generate_silver_cmd(ctx, out_path):
    """Generate the Silver notebook body — Alteryx tools -> pandas/PySpark."""
    from .generate import generate_silver
    code = generate_silver(ctx.obj["ir"], ctx.obj["llm"])
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(code, encoding="utf-8")
    click.echo(f"Wrote {out_path} ({len(code)} chars)")


@generate.command("gold")
@click.option("--out", "out_path", default="notebooks/nb_gold.py")
@click.pass_context
def generate_gold_cmd(ctx, out_path):
    """Generate the Gold notebook body — final outputs from silver tables."""
    from .generate import generate_gold
    code = generate_gold(ctx.obj["ir"], ctx.obj["llm"])
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(code, encoding="utf-8")
    click.echo(f"Wrote {out_path} ({len(code)} chars)")


@generate.command("all")
@click.option("--inputs", "inputs_dir", default="inputs", help="Local inputs directory.")
@click.option("--out-dir", default="notebooks", help="Notebook body output directory.")
@click.pass_context
def generate_all_cmd(ctx, inputs_dir, out_dir):
    """Generate Bronze, Silver, and Gold notebook bodies."""
    from .generate import generate_bronze, generate_gold, generate_silver
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)
    bodies = {
        "nb_bronze.py": generate_bronze(ctx.obj["ir"], Path(inputs_dir), ctx.obj["llm"]),
        "nb_silver.py": generate_silver(ctx.obj["ir"], ctx.obj["llm"]),
        "nb_gold.py": generate_gold(ctx.obj["ir"], ctx.obj["llm"]),
    }
    from .notebooks import validate_notebook_body
    for filename, code in bodies.items():
        issues = validate_notebook_body(code)
        if issues:
            raise click.ClickException(f"{filename}: {'; '.join(issues)}")
        (target / filename).write_text(code, encoding="utf-8")
        click.echo(f"Wrote {target / filename} ({len(code)} chars)")


@main.command("package-notebooks")
@click.option("--notebooks-dir", default="notebooks", help="Directory containing generated .py bodies.")
@click.option("--out-dir", default="notebooks/packaged", help="Destination for complete .ipynb files.")
def package_notebooks_cmd(notebooks_dir: str, out_dir: str):
    """Validate and package generated bodies as complete Fabric notebooks."""
    from .deploy import NOTEBOOK_FILES
    from .notebooks import package_notebook
    st = _state.load(_project_root())
    required = ("workspace_id", "lakehouse_id", "lakehouse_name")
    missing = [key for key in required if not st.get(key)]
    if missing:
        raise click.ClickException(f"Missing state values: {', '.join(missing)}. Run `a2f provision` first.")
    for suffix, filename in NOTEBOOK_FILES.items():
        target = Path(out_dir) / filename.replace(".py", ".ipynb")
        package_notebook(
            Path(notebooks_dir) / filename, target, suffix.replace("_", " "),
            st["workspace_id"], st["lakehouse_id"], st["lakehouse_name"],
        )
        click.echo(f"Wrote {target}")


@main.command("migrate")
@click.argument("yxmd_path")
@click.option("--inputs", "inputs_dir", default="inputs", help="Local input files.")
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github")
@click.option("--model", default=None)
@click.option("--to-fabric", is_flag=True, help="Provision, upload, and deploy after local generation.")
@click.option("--run-pipeline", is_flag=True, help="Run the deployed pipeline.")
@click.option("--reference", "reference_dir", default="reference_outputs", help="Alteryx reference outputs.")
@click.option("--outputs", "outputs_dir", default="fabric_outputs", help="Downloaded Fabric outputs.")
@click.option("--atol", default=1e-3, help="Numeric parity tolerance.")
@click.option("--yes", is_flag=True, help="Approve Fabric writes and review-required mappings.")
@click.option("--restart", is_flag=True, help="Rerun completed stages.")
def migrate_cmd(yxmd_path: str, inputs_dir: str, provider: str, model: str | None,
                to_fabric: bool, run_pipeline: bool, reference_dir: str, outputs_dir: str,
                atol: float, yes: bool, restart: bool):
    """Run or resume parse, plan, generation, preflight, and optional deployment."""
    from .generate import generate_bronze, generate_gold, generate_silver
    from .migration import MigrationManifest
    from .notebooks import validate_notebook_body
    from .plan import build_plan, save_plan
    from .preflight import run_checks

    root = Path(_project_root())
    source = Path(yxmd_path)
    if not source.is_file():
        raise click.ClickException(f"Workflow not found: {source}")
    manifest = MigrationManifest(root, source)
    if restart:
        manifest.reset()

    try:
        if manifest.should_run("parse"):
            ir = parse_yxmd(source)
            save_ir(ir, root / "ir.json")
            manifest.completed("parse", f"Parsed {len(ir.get('tools', []))} tools")
        else:
            ir = _load_ir(str(root / "ir.json"))
            click.echo("[resume] parse already completed")

        if manifest.should_run("plan"):
            migration_plan = build_plan(ir, str(source.resolve()))
            save_plan(migration_plan, root / ".a2f/migration-plan.json", root / ".a2f/migration-plan.md")
            manifest.completed("plan", migration_plan["summary"]["recommendation"], migration_plan["summary"])
        else:
            migration_plan = json.loads((root / ".a2f/migration-plan.json").read_text(encoding="utf-8"))
            click.echo("[resume] plan already completed")

        recommendation = migration_plan["summary"]["recommendation"]
        if recommendation == "review_required" and not yes:
            raise click.ClickException(
                "The plan contains manual/high-risk mappings. Review .a2f/migration-plan.md and rerun with --yes."
            )

        if manifest.should_run("generate"):
            llm = _llm(provider, model)
            target = root / "notebooks"
            target.mkdir(exist_ok=True)
            bodies = {
                "nb_bronze.py": generate_bronze(ir, Path(inputs_dir), llm),
                "nb_silver.py": generate_silver(ir, llm),
                "nb_gold.py": generate_gold(ir, llm),
            }
            for filename, body in bodies.items():
                issues = validate_notebook_body(body)
                if issues:
                    raise ValueError(f"{filename}: {'; '.join(issues)}")
                (target / filename).write_text(body, encoding="utf-8")
            manifest.completed("generate", "Generated and validated three notebook bodies")
        else:
            click.echo("[resume] generation already completed")

        checks = run_checks(root, online=to_fabric)
        blockers = [
            check for check in checks
            if check.status == "fail" and (to_fabric or check.name != "azure_cli")
        ]
        if blockers:
            raise ValueError("; ".join(f"{check.name}: {check.message}" for check in blockers))
        manifest.completed("preflight", "Local preflight passed")

        if not to_fabric:
            click.secho("Local migration artifacts are ready. Use --to-fabric --yes to deploy.", fg="green")
            return
        if not yes:
            raise click.ClickException("Fabric writes require explicit approval with --yes.")

        ctx = click.get_current_context()
        if manifest.should_run("provision"):
            ctx.invoke(provision, lakehouse_name=None)
            manifest.completed("provision", "Lakehouse ready")
        if manifest.should_run("upload"):
            ctx.invoke(upload, local_dir=inputs_dir, remote_prefix="Input")
            manifest.completed("upload", "Inputs uploaded")
        if manifest.should_run("deploy"):
            ctx.invoke(deploy, notebooks_dir="notebooks", prefix="Nb", pipeline_name=None,
                       ir_path="ir.json", no_parameters=False)
            manifest.completed("deploy", "Notebooks and pipeline deployed")
        if run_pipeline and manifest.should_run("run"):
            ctx.invoke(run, pipeline_name=None, timeout=1800, params=())
            manifest.completed("run", "Pipeline completed")
        if run_pipeline and manifest.should_run("validate"):
            references = Path(reference_dir)
            reference_files = [path for path in references.rglob("*") if path.is_file()] if references.is_dir() else []
            if not reference_files:
                manifest.mark("validate", "skipped", "No reference outputs were supplied")
                click.secho("Validation skipped: no reference outputs were found.", fg="yellow")
            else:
                ctx.invoke(download, remote_path="Files/Output", out_dir=outputs_dir)
                results = diff_folders(reference_dir, outputs_dir, atol=atol)
                click.echo(format_report(results))
                if not all(result.passed for result in results):
                    raise ValueError("Fabric output parity validation failed.")
                manifest.completed("validate", f"Validated {len(results)} output file(s)")
    except click.ClickException:
        raise
    except Exception as exc:
        active = next((stage for stage in ("parse", "plan", "generate", "preflight", "provision", "upload", "deploy", "run")
                       if manifest.should_run(stage)), "preflight")
        manifest.failed(active, exc)
        raise click.ClickException(str(exc)) from exc


@main.command()
@click.argument("tool_id")
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github")
@click.option("--model", default=None)
@click.option("--ir", "ir_path", default="ir.json")
def explain(tool_id, provider, model, ir_path):
    """Plain-English explanation of one Alteryx tool from the IR."""
    from .generate import explain_tool
    ir = _load_ir(ir_path)
    click.echo(explain_tool(ir, tool_id, _llm(provider, model)))


@main.command()
@click.option("--notebook", "nb_path", required=True, help="Path to notebook .py to patch.")
@click.option("--diff", "diff_path", required=True, help="Path to validate report (text).")
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github")
@click.option("--model", default=None)
def fix(nb_path, diff_path, provider, model):
    """Patch a notebook to resolve a validation diff."""
    from .generate import fix_from_diff
    diff_text = Path(diff_path).read_text(encoding="utf-8")
    patched = fix_from_diff(Path(nb_path), diff_text, _llm(provider, model))
    Path(nb_path).write_text(patched, encoding="utf-8")
    click.echo(f"Patched {nb_path} ({len(patched)} chars)")


# ----------------------------- analyze -----------------------------
@main.command()
@click.argument("workflow_dir")
@click.option("--out", "out_dir", default="analysis", help="Output folder for CSV/XLSX reports.")
@click.option("--near-threshold", default=0.9, type=float,
              help="Jaccard similarity threshold for near-duplicate clusters (0..1).")
def analyze(workflow_dir: str, out_dir: str, near_threshold: float):
    """Batch-analyze a folder of .yxmd files: report, dependencies, duplicates."""
    from .analyze import analyze_dir
    src = Path(workflow_dir)
    if not src.exists():
        click.secho(f"Folder not found: {workflow_dir}", fg="red"); sys.exit(2)
    result = analyze_dir(src, Path(out_dir), near_threshold=near_threshold)
    click.echo(f"Analyzed {result['file_count']} workflow file(s).")
    click.echo(f"  Dependency edges:    {result['dependency_edges']}")
    click.echo(f"  Duplicate clusters:  {result['duplicate_clusters']}")
    click.echo("Outputs:")
    for k, v in result["written"].items():
        click.echo(f"  {k:<22} {v}")


if __name__ == "__main__":
    main()
