"""`a2f` command-line interface."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import click

from . import __version__, state as _state
from .fabric_api import FabricClient
from .onelake import OneLake
from .parse import parse_yxmd, save_ir, summarise
from .deploy import deploy_default_notebooks, deploy_pipeline
from .run import run_pipeline_and_wait
from .validate import diff_folders, format_report


# ----------------------------- helpers -----------------------------
def _project_root() -> str:
    return os.getcwd()


def _get_client_or_exit() -> FabricClient:
    st = _state.load(_project_root())
    ws = st.get("workspace_id") or os.environ.get("A2F_WORKSPACE_ID")
    if not ws:
        click.secho(
            "Error: workspace_id not set. Run `a2f init <name> --workspace-id <guid>` "
            "or set A2F_WORKSPACE_ID.",
            fg="red",
        )
        sys.exit(2)
    return FabricClient(ws)


# ----------------------------- root group -----------------------------
@click.group()
@click.version_option(__version__, prog_name="a2f")
def main():
    """alteryx2fabric — migrate Alteryx workflows to Microsoft Fabric."""


# ----------------------------- init -----------------------------
@main.command()
@click.argument("name")
@click.option("--workspace-id", required=True, help="Fabric workspace GUID.")
@click.option("--lakehouse-name", default=None, help="Lakehouse display name to use (default: <name>_LH).")
def init(name: str, workspace_id: str, lakehouse_name: str | None):
    """Scaffold a new migration project in ./<NAME>/."""
    root = Path(name)
    if root.exists():
        click.secho(f"Refusing to overwrite existing path: {root}", fg="red")
        sys.exit(2)
    for d in ("inputs", "reference_outputs", "fabric_outputs", "notebooks", ".a2f"):
        (root / d).mkdir(parents=True, exist_ok=True)
    state = {
        "project_name": name,
        "workspace_id": workspace_id,
        "lakehouse_name": lakehouse_name or f"{name}_LH",
    }
    _state.save(state, root)
    (root / "README.md").write_text(
        f"# {name}\n\nGenerated by alteryx2fabric.\n\n"
        "- `inputs/`            — source files to upload to OneLake\n"
        "- `reference_outputs/` — Alteryx-produced files used for validation\n"
        "- `fabric_outputs/`    — files downloaded from Fabric after a run\n"
        "- `notebooks/`         — generated `.ipynb` cache\n"
        "- `.a2f/state.json`    — Fabric IDs for subsequent commands\n",
        encoding="utf-8",
    )
    click.secho(f"Initialised project: {root.resolve()}", fg="green")
    click.echo(f"  workspace_id  = {workspace_id}")
    click.echo(f"  lakehouse     = {state['lakehouse_name']}")


# ----------------------------- doctor -----------------------------
@main.command()
def doctor():
    """Preflight: check az login, workspace access."""
    from .auth import get_tenant_and_user
    try:
        tenant, user = get_tenant_and_user()
        click.echo(f"az tenant: {tenant}")
        click.echo(f"az user:   {user}")
    except Exception as e:
        click.secho(f"az check failed: {e}", fg="red")
        sys.exit(2)

    st = _state.load(_project_root())
    ws = st.get("workspace_id")
    if not ws:
        click.secho("workspace_id not set in .a2f/state.json", fg="yellow")
        return
    client = FabricClient(ws)
    items = client.list_items()
    click.echo(f"workspace {ws}: {len(items)} items")


# ----------------------------- parse -----------------------------
@main.command()
@click.argument("yxmd_path")
@click.option("--out", "out_path", default="ir.json", help="Where to write the IR JSON.")
def parse(yxmd_path: str, out_path: str):
    """Parse an Alteryx workflow into a JSON Intermediate Representation."""
    ir = parse_yxmd(yxmd_path)
    save_ir(ir, out_path)
    click.echo(summarise(ir))
    click.secho(f"\nIR written: {out_path}", fg="green")


# ----------------------------- provision -----------------------------
@main.command()
@click.option("--lakehouse", "lakehouse_name", default=None, help="Lakehouse name (defaults to state).")
def provision(lakehouse_name: str | None):
    """Create the Lakehouse in the workspace."""
    client = _get_client_or_exit()
    st = _state.load(_project_root())
    name = lakehouse_name or st.get("lakehouse_name")
    if not name:
        click.secho("lakehouse name not provided", fg="red"); sys.exit(2)
    lh = client.create_lakehouse(name)
    click.secho(f"Lakehouse ready: {lh['displayName']} ({lh['id']})", fg="green")
    _state.update({"lakehouse_id": lh["id"], "lakehouse_name": lh["displayName"]}, _project_root())


# ----------------------------- upload -----------------------------
@main.command()
@click.argument("local_dir")
@click.option("--to", "remote_prefix", default="Input", help="Remote subfolder under Files/.")
def upload(local_dir: str, remote_prefix: str):
    """Upload all files under LOCAL_DIR to OneLake Files/<TO>/."""
    st = _state.load(_project_root())
    ws = st.get("workspace_id")
    lh_name = st.get("lakehouse_name")
    if not (ws and lh_name):
        click.secho("workspace_id / lakehouse_name missing — run init + provision first.", fg="red")
        sys.exit(2)
    ol = OneLake(ws, lh_name)
    src = Path(local_dir)
    n = 0
    for p in sorted(src.iterdir()):
        if p.is_file():
            size = ol.upload(p, f"{remote_prefix}/{p.name}")
            click.echo(f"uploaded {p.name} ({size} bytes)")
            n += 1
    click.secho(f"{n} files uploaded to Files/{remote_prefix}/", fg="green")


# ----------------------------- deploy -----------------------------
@main.command()
@click.option("--inputs-config", default=None, help="JSON file describing bronze inputs.")
@click.option("--prefix", default="Nb", help="Notebook name prefix.")
@click.option("--pipeline-name", default=None, help="Data Pipeline name (default: PL_<project>_Run).")
def deploy(inputs_config: str | None, prefix: str, pipeline_name: str | None):
    """Deploy Bronze/Silver/Gold notebooks and the orchestration pipeline."""
    client = _get_client_or_exit()
    st = _state.load(_project_root())
    lh_id = st.get("lakehouse_id")
    lh_name = st.get("lakehouse_name")
    if not lh_id:
        click.secho("Lakehouse not provisioned. Run `a2f provision` first.", fg="red"); sys.exit(2)

    if inputs_config and Path(inputs_config).exists():
        inputs = json.loads(Path(inputs_config).read_text(encoding="utf-8"))
    else:
        inputs = [{"table": "example", "file": "example.csv"}]
        click.secho("No --inputs-config provided; deploying with a placeholder bronze cell.", fg="yellow")

    nb_ids = deploy_default_notebooks(client, inputs, lh_id, lh_name, prefix=prefix)
    for name, _id in nb_ids.items():
        click.echo(f"  notebook {name}: {_id}")

    pl_name = pipeline_name or f"PL_{st.get('project_name', 'Migration')}_Run"
    chain = [
        ("Bronze Ingest", nb_ids[f"{prefix}_Bronze_Ingest"]),
        ("Silver Transform", nb_ids[f"{prefix}_Silver_Transform"]),
        ("Gold Outputs", nb_ids[f"{prefix}_Gold_Outputs"]),
    ]
    pid = deploy_pipeline(client, pl_name, chain)
    click.secho(f"Pipeline {pl_name}: {pid}", fg="green")
    _state.update({"notebooks": nb_ids, "pipeline_name": pl_name, "pipeline_id": pid}, _project_root())


# ----------------------------- run -----------------------------
@main.command()
@click.option("--pipeline", "pipeline_name", default=None, help="Pipeline name (default: from state).")
@click.option("--timeout", default=1800, help="Timeout in seconds.")
def run(pipeline_name: str | None, timeout: int):
    """Trigger the pipeline and stream status."""
    client = _get_client_or_exit()
    st = _state.load(_project_root())
    pid = st.get("pipeline_id")
    if pipeline_name:
        item = client.find_item(pipeline_name, "DataPipeline")
        if not item:
            click.secho(f"Pipeline '{pipeline_name}' not found.", fg="red"); sys.exit(2)
        pid = item["id"]
    if not pid:
        click.secho("No pipeline id — run `a2f deploy` first or pass --pipeline.", fg="red"); sys.exit(2)

    click.echo(f"Triggering pipeline {pid} ...")
    status_url, progress, final = run_pipeline_and_wait(client, pid, timeout_s=timeout)
    for elapsed, status in progress:
        click.echo(f"  [{elapsed}s] status={status}")
    click.echo("Final:")
    click.echo(json.dumps(final, indent=2)[:1500])
    if final.get("status") != "Completed":
        sys.exit(1)


# ----------------------------- download -----------------------------
@main.command()
@click.argument("remote_path")
@click.option("--out", "out_dir", default="fabric_outputs", help="Local destination dir.")
def download(remote_path: str, out_dir: str):
    """Download a file or all files in a remote folder from OneLake Files/."""
    st = _state.load(_project_root())
    ws = st.get("workspace_id")
    lh_name = st.get("lakehouse_name")
    ol = OneLake(ws, lh_name)
    dest = Path(out_dir); dest.mkdir(parents=True, exist_ok=True)
    # Try as folder first
    try:
        paths = ol.list_dir(remote_path)
        files = [p for p in paths if not p.get("isDirectory")]
        if files:
            for p in files:
                # path looks like Files/<remote_path>/foo.xlsx
                name = p["name"].split("/")[-1]
                full_remote = p["name"].split("Files/", 1)[-1]
                ol.download(full_remote, dest / name)
                click.echo(f"  downloaded {name} ({p.get('contentLength')} bytes)")
            return
    except Exception:
        pass
    # Fall back to single file
    name = remote_path.rsplit("/", 1)[-1]
    ol.download(remote_path, dest / name)
    click.echo(f"  downloaded {name}")


# ----------------------------- validate -----------------------------
@main.command()
@click.option("--ref", "ref_dir", required=True, help="Reference output folder.")
@click.option("--gen", "gen_dir", required=True, help="Generated (Fabric) output folder.")
@click.option("--atol", default=1e-3, help="Numeric tolerance.")
def validate(ref_dir: str, gen_dir: str, atol: float):
    """Diff two folders of result files (xlsx/csv/parquet)."""
    results = diff_folders(ref_dir, gen_dir, atol=atol)
    click.echo(format_report(results))
    if not all(r.passed for r in results):
        sys.exit(1)


# ----------------------------- AI commands -----------------------------
def _llm(provider: str, model: str | None):
    from .ai import LLMClient
    return LLMClient(provider=provider, model=model)


def _load_ir(ir_path: str) -> dict:
    p = Path(ir_path)
    if not p.exists():
        click.secho(f"IR not found at {ir_path}. Run `a2f parse <yxmd> --out ir.json` first.", fg="red")
        sys.exit(2)
    return json.loads(p.read_text(encoding="utf-8"))


@main.group()
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github",
              help="LLM provider. github = GitHub Models (uses GITHUB_TOKEN/gh auth).")
@click.option("--model", default=None, help="Model id override (e.g. anthropic/claude-opus-4).")
@click.option("--ir", "ir_path", default="ir.json", help="Path to IR JSON from `a2f parse`.")
@click.pass_context
def generate(ctx, provider, model, ir_path):
    """AI-assisted notebook generation."""
    ctx.ensure_object(dict)
    ctx.obj["llm"] = _llm(provider, model)
    ctx.obj["ir"] = _load_ir(ir_path)


@generate.command("bronze")
@click.option("--inputs", "inputs_dir", default="inputs", help="Local inputs directory.")
@click.option("--out", "out_path", default="notebooks/nb_bronze.py", help="Output file.")
@click.pass_context
def generate_bronze_cmd(ctx, inputs_dir, out_path):
    """Generate the Bronze notebook body from the IR + local input headers."""
    from .generate import generate_bronze
    code = generate_bronze(ctx.obj["ir"], Path(inputs_dir), ctx.obj["llm"])
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(code, encoding="utf-8")
    click.echo(f"Wrote {out_path} ({len(code)} chars)")


@generate.command("silver")
@click.option("--out", "out_path", default="notebooks/nb_silver.py")
@click.pass_context
def generate_silver_cmd(ctx, out_path):
    """Generate the Silver notebook body — Alteryx tools -> pandas/PySpark."""
    from .generate import generate_silver
    code = generate_silver(ctx.obj["ir"], ctx.obj["llm"])
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(code, encoding="utf-8")
    click.echo(f"Wrote {out_path} ({len(code)} chars)")


@generate.command("gold")
@click.option("--out", "out_path", default="notebooks/nb_gold.py")
@click.pass_context
def generate_gold_cmd(ctx, out_path):
    """Generate the Gold notebook body — final outputs from silver tables."""
    from .generate import generate_gold
    code = generate_gold(ctx.obj["ir"], ctx.obj["llm"])
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(code, encoding="utf-8")
    click.echo(f"Wrote {out_path} ({len(code)} chars)")


@main.command()
@click.argument("tool_id")
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github")
@click.option("--model", default=None)
@click.option("--ir", "ir_path", default="ir.json")
def explain(tool_id, provider, model, ir_path):
    """Plain-English explanation of one Alteryx tool from the IR."""
    from .generate import explain_tool
    ir = _load_ir(ir_path)
    click.echo(explain_tool(ir, tool_id, _llm(provider, model)))


@main.command()
@click.option("--notebook", "nb_path", required=True, help="Path to notebook .py to patch.")
@click.option("--diff", "diff_path", required=True, help="Path to validate report (text).")
@click.option("--provider", type=click.Choice(["github", "anthropic"]), default="github")
@click.option("--model", default=None)
def fix(nb_path, diff_path, provider, model):
    """Patch a notebook to resolve a validation diff."""
    from .generate import fix_from_diff
    diff_text = Path(diff_path).read_text(encoding="utf-8")
    patched = fix_from_diff(Path(nb_path), diff_text, _llm(provider, model))
    Path(nb_path).write_text(patched, encoding="utf-8")
    click.echo(f"Patched {nb_path} ({len(patched)} chars)")


if __name__ == "__main__":
    main()
